Repository CMPUT291PROJECTF18/Mini-Project-1, pull requests merged in 2018-11, with the labels that each got.

#20 Implemented basic cancel_booking functionality (Resolves #9)
  mini_project_1/shell.py
Labels: enhancement

#24 Feature/rides offer
  mini_project_1/member.py
  mini_project_1/ride.py
  mini_project_1/shell.py
Labels: enhancement

#22 Feature/post ride request
  mini_project_1/data/create_data.sql
  mini_project_1/shell.py
  setup.py
Labels: enhancement

#33 using `self.login_session` over `self.login_member`
  mini_project_1/shell.py
Labels: bug

#34 Feature/login on start
  mini_project_1/__main__.py
  mini_project_1/loginsession.py
  mini_project_1/shell.py
  test/unit/test_database.py
Labels: enhancement

#37 Implemented basic search_ride_request* functionality (resolves #5, resolves #31)
  mini_project_1/shell.py
Labels: enhancement

#40 WIP: adding registration functionality
  mini_project_1/__init__.py
  mini_project_1/register.py
  setup.py
  test/unit/test_database.py
Labels: enhancement

#43 Feature/messaging
  mini_project_1/data/create_data.sql
  mini_project_1/shell.py
Labels: enhancement

#51 refactoring push
  mini_project_1/__init__.py
  mini_project_1/cancel_booking.py
  mini_project_1/common.py
  mini_project_1/delete_ride_request.py
  mini_project_1/loginsession.py
  mini_project_1/post_ride_request.py
  mini_project_1/register.py
  mini_project_1/ride.py
  mini_project_1/search_ride_requests.py
  mini_project_1/select_ride_request.py
  mini_project_1/shell.py
  test/unit/test_cmd_engine.py
Labels: documentation, enhancement

#59 refactoring more functionality
  mini_project_1/__init__.py
  mini_project_1/__main__.py
  mini_project_1/book_member.py
  mini_project_1/cancel_booking.py
  mini_project_1/common.py
  mini_project_1/delete_ride_request.py
  mini_project_1/offer_ride.py
  mini_project_1/post_ride_request.py
  mini_project_1/register.py
  mini_project_1/search_ride_requests.py
  mini_project_1/search_rides.py
  mini_project_1/select_ride_request.py
  mini_project_1/shell.py
Labels: documentation, enhancement

#74 updating docs
  mini_project_1/shell.py
Labels: documentation

#81 Feature/improved help
  mini_project_1/book_member.py
  mini_project_1/cancel_booking.py
  mini_project_1/delete_request.py
  mini_project_1/list_bookings.py
  mini_project_1/list_requests.py
  mini_project_1/logout.py
  mini_project_1/offer_ride.py
  mini_project_1/post_request.py
  mini_project_1/search_requests.py
  mini_project_1/search_rides.py
  mini_project_1/select_request.py
  mini_project_1/shell.py
  mini_project_1/show_inbox.py
  test/unit/test_database.py
Labels: documentation

#83 Feature/refactoring level3
  mini_project_1/__init__.py
  mini_project_1/book_member.py
  mini_project_1/cancel_booking.py
  mini_project_1/common.py
  mini_project_1/delete_request.py
  mini_project_1/list_bookings.py
  mini_project_1/list_requests.py
  mini_project_1/logout.py
  mini_project_1/offer_ride.py
  mini_project_1/post_request.py
  mini_project_1/search_requests.py
  mini_project_1/search_rides.py
  mini_project_1/select_request.py
  mini_project_1/shell.py
  mini_project_1/show_inbox.py
  test/unit/test_database.py
Labels: enhancement

#85 Feature/usage docs
  docs/commands.rst
  docs/index.rst
  docs/shellcommands.rst
  mini_project_1/book_member.py
  mini_project_1/common.py
  mini_project_1/offer_ride.py
  mini_project_1/post_request.py
  mini_project_1/shell.py
Labels: documentation

#89 Update setup.py
  LICENSE
  README.rst
  docs/index.rst
  setup.py
Labels: bug
